name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS: no container, use setup-swift
          - os: macos-latest
            swift: "6.0"

          # Linux: run inside official Swift container (no setup-swift needed)
          - os: ubuntu-24.04
            swift: "6.0"
            container: swift:6.0-jammy

    # Only applies to the Ubuntu row
    container: ${{ matrix.container }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # macOS: cache .build + ~/.swiftpm
      - name: Cache SPM (macOS)
        if: runner.os == 'macOS'
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.swiftpm
          key: ${{ runner.os }}-swift-${{ matrix.swift }}-${{ hashFiles('**/Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-swift-${{ matrix.swift }}-

      # macOS only — install toolchain
      - name: Set up Swift ${{ matrix.swift }} (macOS)
        if: runner.os == 'macOS'
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}

      # Linux container already has Swift

      - name: Resolve dependencies
        run: swift package resolve

      - name: Build
        run: swift build -v

      - name: Test (parallel, with coverage)
        run: swift test --parallel --enable-code-coverage

      - name: Collect coverage (LLVM JSON)
        if: always()
        run: |
          mkdir -p coverage
          llvm-profdata merge -sparse .build/**/*.profdata -o coverage/coverage.profdata || true
          cp -R .build/*/codecov* coverage/ 2>/dev/null || true

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-swift-${{ matrix.swift }}
          path: coverage
